### ISSUE TITLE
Init doesnt work in ldmx-sw docker version

### ISSUE THREAD

**Issue by tvami** [tomeichlersmith/denv#139]
I think https://github.com/tomeichlersmith/denv/pull/138 changed things for ldmx-sw unintentionally when using docker (or MacOS)

```
cd /tmp
git clone --recursive git@github.com:LDMX-Software/ldmx-sw.git
cd ldmx-sw/
just install-denv
just init
```
gives
```
ERROR: Unable to deduce a denv workspace
       You may need to just 'denv init' in the directory of your choice.
```
while in the past it started to download the image. Maybe the the ldmx meaning if `init` needs to change?
There is clearly no other .denv around it, it's the first time I'm in `/tmp/` to test this (because Filippo has seen this error)

The `.denv` dir is created and 
```
tav@Tamass-MacBook-Pro /tmp/ldmx-sw $ denv config print
denv_workspace="/private/tmp"
denv_name="ldmx"
denv_image="ldmx/dev:latest"
denv_mounts=""
denv_shell="/bin/bash -i"
denv_network="true"
Docker version 27.2.0, build 3ab4256
DISPLAY=host.docker.internal:0
DENV_NAME=ldmx
DENV_RUNNER=docker
DENV_IMAGE=ldmx/dev:latest
HOME=/private/tmp
```
but then
```
ls ../.denv/
.gitignore  config      skel-init   
```

The same thing in `apptainer` on POD works according to expectation. 
```
.denv/
[vamitamas@pod-login1 .denv]$ l
total 2.5K
-rw-r--r-- 1 vamitamas incandela 164 Oct  1 19:01 .gitignore
-rw-r--r-- 1 vamitamas incandela 178 Oct  1 19:01 config
drwxr-xr-x 2 vamitamas incandela   1 Oct  1 19:03 images
-rw-r--r-- 1 vamitamas incandela   0 Oct  1 19:08 skel-init
drwxr-xr-x 5 vamitamas incandela   6 Oct  1 19:10 ..
drwxr-xr-x 3 vamitamas incandela   4 Oct  1 19:10 .
```

the config is the same
```
denv config print
denv_workspace="/home/vamitamas/iss1482-ecal-pos-verify"
denv_name="ldmx"
denv_image="ldmx/dev:latest"
denv_mounts=""
denv_shell="/bin/bash -i"
denv_network="true"
apptainer version 1.2.5
DISPLAY=localhost:12.0
DENV_NAME=ldmx
DENV_RUNNER=apptainer
DENV_IMAGE=ldmx/dev:latest

```

Let me know if you consider this to be better placed in ldmx-sw issue than here

**Comment by tomeichlersmith** [comment]
So the good news is that I don't think this is an actual error and is just coming from `denv check`. There, I made the choice to not silence the errors and so the error you see is printed when a workspace is not found (as it says).

https://github.com/tomeichlersmith/denv/blob/e655a830099b4910d704960da599702575e1fbbc/denv#L1140-L1141

The annoyance for us is that `just init` immediately follows up a failure-to-find-workspace by running the appropriate `denv init` call. The solution I think is therefore to silence the errors as well as the other messages when `--quiet` is specified in `denv check`.

---

You aren't seeing an image download on MacOS because docker does a better job of image deduplication than apptainer. When running with apptainer, we convert an OCI image into a SIF image so that it can be run later while docker runs directly from the OCI image. The SIF image is stored in `.denv/images/` so that `denv` can find it, but this also means that each workspace has its own copy of the SIF images and needs its own one built.
