### ISSUE TITLE
Check executable might not be available on all platforms

### ISSUE THREAD

**Issue by EinarElen** [tomeichlersmith/denv#87]
**Describe the bug**
Running `denv check` on a MacOs system is likely to result in 
```shell
sh: 1: check: not found
```
since check isn't installed by default. This can be resolved by the user installing it (e.g. brew install check), but it might be worth working around to make denv easier to use for people

**Comment by EinarElen** [comment]
Or maybe this is a different issue... check doesn't seem to be a part of denv anymore but is part of the README

**Comment by tomeichlersmith** [comment]
So, `check` should be a sub-command that just runs some extra shell stuff:

https://github.com/tomeichlersmith/denv/blob/e23273fe081138c7b76a23ca13d9ef7e6ac90550/denv#L917

It was very recently introduced, it is not within `denv v0.5.0`. You could either skip this check or use `<curl install> | sh -- --next` to install from the HEAD of main.

**Comment by EinarElen** [comment]
Right, I don't really mind just wanted to highlight the README discrepancy on main :)

**Comment by tomeichlersmith** [comment]
Yep :+1: Thank you, I need to think more about how to keep the docs from getting out of sync with the latest version.

**Comment by tomeichlersmith** [comment]
Alright, I made a new release which will allow for the installed version and what is documented on the README to be in sync. I think I just need to be more cognizant of the fact that anything that changes the CLI (especially anything changing basic usage shown in the README) mandates a new release so that installers do end up in this situation.
